function cfBrandAI(){return '<div class="cf27-brand"><span class="cf27-ai" aria-label="AI-powered">AI</span><img src="assets/connectfacts/logo.svg" alt="ConnectFacts" width="145" height="66"></div>';}
function renderConnectFactsAI(){return `
<section class="cf27-hero wrap">
 <div class="cf27-intro"><div>${cfBrandAI()}<p class="eyebrow">FOR TMT PLANT LEADERS</p><h1>Every heat.<br>Every minute.<br><span>Every decision.</span></h1></div><div class="cf27-lede"><p>ConnectFacts, now AI-powered.</p><p>Connect your furnace, caster and rolling mill. See what needs attention and get timely alerts on the phones your team already uses.</p><a class="btn btn-blue" href="https://connectfacts.com/">Explore ConnectFacts AI</a><span>Capture. See. Act.</span></div></div>
 <figure class="cf27-screen"><div class="cf27-screen-head"><span>MELT–CAST–ROLL CONTROL TOWER</span><span>One plant. One operating view.</span></div><a href="assets/connectfacts/control-tower-ai.webp" target="_blank" rel="noopener" aria-label="View the Control Tower dashboard at full size"><img src="assets/connectfacts/control-tower-ai.webp" width="2880" height="1260" alt="ConnectFacts Control Tower showing plant output, heat timing, priorities and section performance"></a><figcaption>ConnectFacts Control Tower <span>Open the image to explore the dashboard</span></figcaption></figure>
</section>
<section class="cf18-value wrap"><div class="cf18-head"><p class="eyebrow">FROM THE PLANT FLOOR TO YOUR PHONE</p><h2>Capture the facts.<br><span>Act while it matters.</span></h2></div><div class="cf18-three">${[
['01','Capture','PLCs and energy meters capture readings every minute. Tablets record the rest in Hindi and regional languages. An on-site server retains data even offline.','100+ data points on every heat'],
['02','See','The Control Tower connects melt, cast and roll in one view. Review any minute of the day, on your desk or on your phone.','One view across your plant'],
['03','Act','An AI agent checks furnace data every five minutes, assesses whether an issue is real and new, and sends a clear alert on WhatsApp or Telegram.','Relevant alerts, without repeats']
].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><strong class="cf27-detail">${x[3]}</strong></article>`).join('')}</div></section>
<section class="cf27-intelligence"><div class="wrap cf27-split"><div><p class="eyebrow">BUILT-IN INTELLIGENCE</p><h2>Know what<br><span>to fix first.</span></h2><div class="cf27-features">${[
['Priorities with ownership','Issues ranked P1 to P3 by the tonnes at stake, with an owner and a deadline.'],
['Evidence for the next check','See the observation, likely cause, supporting evidence and the check to run next.'],
['A four-hour look ahead','Identify when a late tap could leave the caster without metal, giving the team time to respond.']
].map(x=>`<article><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div><figure><a href="assets/connectfacts/priorities-ai.webp" target="_blank" rel="noopener" aria-label="View prioritised actions and production losses at full size"><img src="assets/connectfacts/priorities-ai.webp" width="2720" height="1962" alt="ConnectFacts prioritised actions with owners, deadlines and throughput loss analysis" loading="lazy"></a><figcaption>Ranked actions and the tonnes at stake.</figcaption></figure></div></section>
<section class="cf27-alerts wrap"><div><p class="eyebrow">AI ALERTS</p><h2>Your plant’s signals.<br><span>On your team’s phones.</span></h2><p>Slow power, a heat running too long, or a shift summary. The agent checks whether an event needs attention and whether the team has already been told.</p><div class="cf27-channels"><span>WhatsApp</span><span>Telegram</span></div></div><div class="cf27-messages" aria-label="Illustrative alert messages based on the presentation"><p class="eyebrow">EXAMPLE PLANT ALERTS</p><article><span>POWER DEVIATION</span><h3>F04 · Heat 3 · Slow power</h3><p>Since 13:34 · 3.9 minutes so far<br>Power: 3,452 kW</p></article><article><span>CYCLE TIME</span><h3>F02 · Heat 4 · Running too long</h3><p>3 hours 43 minutes<br>Target: 3 hours</p></article><small>Illustrative messages from the September 2026 presentation.</small></div></section>
<section class="cf27-pilot"><div class="wrap"><p class="eyebrow">AI PILOT · SMEL UNIT 1</p><h2>A furnace slowed at 10:06.<br>The team knew at 10:10.</h2><div class="cf27-metrics">${[['5','furnaces monitored live'],['5 min','reported problem-to-phone time'],['100%','match with the ConnectFacts report'],['0','extra operator data entry']].map(x=>`<div><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div><p class="cf27-note">Pilot: 16–21 September 2026. Events were checked against the ConnectFacts slow-power report for completed heats. These results describe this pilot.</p></div></section>
<section class="cf27-results wrap"><p class="eyebrow">LFC PROGRAMME RESULTS</p><h2>Operational improvement.<br><span>Measured on the floor.</span></h2><div class="cf27-result-grid">${[
['TMT bar maker','+21%','mill production','Furnace production increased 16%; expansion capex avoided.'],
['Distressed steel unit','28% to 47%','OEE in six months','Monthly sales rose from 4,500 to 6,000 MT; the plant moved from losses to profits.'],
['Ductile-iron pipe plant','+54%','average monthly throughput','Achieved over 13 months, alongside a 61% reduction in breakdowns.']
].map(x=>`<article><p class="eyebrow">${x[0]}</p><strong>${x[1]}</strong><h3>${x[2]}</h3><p>${x[3]}</p></article>`).join('')}</div><p class="cf27-note">Results from Levers for Change programmes, as reported in the presentation. These are historical engagement outcomes, separate from the AI pilot; client names are withheld.</p></section>
<section class="cf18-close cf27-close"><div class="wrap">${cfBrandAI()}<h2>Start with one plant.</h2><p>Your furnaces. Your data. Your team’s phones.<br>Explore a ConnectFacts AI pilot for your operations.</p><a class="btn btn-blue" href="https://connectfacts.com/">Explore ConnectFacts AI</a></div></section>
`;}
