var CLIENT_MARKS=__CLIENT_MARKS__;
var LEADERS=__LEADERS__;
function leadershipGrid(){
  function group(title,ids,kind){return '<section class="leadership21-group '+kind+'" aria-label="'+title+'"><div class="leadership21-label"><h3>'+title+'</h3><span></span></div><div class="leaders5-grid">'+ids.map(function(i){var l=LEADERS[i],body='<img src="assets/images/leaders/'+l.slug+'.webp" alt="'+esc(l.name)+'" width="1024" height="1024" loading="lazy"><h4>'+esc(l.name)+'</h4><p>'+esc(l.role)+'</p>';return l.linkedin?'<a class="leader5 leader5-link" href="'+l.linkedin+'" target="_blank" rel="noopener noreferrer" aria-label="View '+esc(l.name)+' on LinkedIn">'+body+'<span class="leader5-linkedin" aria-hidden="true">in</span></a>':'<article class="leader5">'+body+'</article>';}).join('')+'</div></section>';}
  return group('Advisory board',[0,1],'leadership21-advisors')+group('Our partners',[2,3,4,5,6,7],'leadership21-partners');
}
function logoRun(hidden){return '<div class="logo5-group"'+(hidden?' aria-hidden="true"':'')+'>'+CLIENT_MARKS.map(function(l){return '<div class="logo5-cell'+(l.dark?' logo28-dark':'')+'"><img src="'+l.src+'" alt="'+(hidden?'':esc(l.name))+'" width="170" height="70" loading="lazy"></div>';}).join('')+'</div>';}
CAPABILITIES[0].image='v6/precision';CAPABILITIES[1].image='v6/growth';CAPABILITIES[3].image='v6/connected';
PAGES['']={title:'Levers for Change | Possibility into progress',nav:'',render:function(){return `
<section class="hero10 wrap" id="overview"><div class="hero10-stage"><img class="hero10-image" src="assets/images/v10/performance-advisor.webp" width="1536" height="1024" fetchpriority="high" alt="Conceptual illustration of a business advisor beside interlocking blue and silver gears, representing aligned operations, people and growth"><div class="hero10-copy"><p class="eyebrow">LEVERS FOR CHANGE</p><h1><span class="line6">Unlock capacity.</span><span class="line6 hero10-accent">Grow profit.</span><span class="line6">Make it last.</span></h1><p class="hero10-lede">The potential is in your business.<br>We help your people turn it into performance.</p><a class="btn btn-blue" href="#/contact">Discover your growth levers</a><div class="hero10-proof"><span><strong>16+</strong>Years</span><span><strong>200+</strong>Transformations</span><span><strong>10+</strong>Countries</span></div></div></div><div class="hero10-outcomes"><span>More productive operations</span><span>Stronger commercial growth</span><span>Results your people can sustain</span></div></section>
<section class="clients5" aria-label="Our clients"><div class="wrap clients5-head"><p class="eyebrow">TRUSTED TO MAKE CHANGE HAPPEN</p><button id="clients28Toggle" type="button" aria-expanded="false" aria-controls="clients28Gallery">Our clients</button></div><div class="logo5-window"><div class="logo5-track">${logoRun(false)}${logoRun(true)}</div></div><div id="clients28Gallery" hidden>${logoStrip()}</div></section>
<section class="intro5 wrap reveal"><div><p class="eyebrow">THE VALUE IS ALREADY THERE.</p><h2>A different perspective.<br><span>A tangible difference.</span></h2></div><div><p>Inside every business are opportunities waiting to be seen. We bring the clarity to find them, the experience to act on them, and the commitment to see the change through.</p><a class="text-link" href="#/how-we-engage">How we work</a></div></section>
<section class="proof5 wrap reveal" aria-label="LFC at a glance"><div><strong data-count6="16" data-suffix6="+">16+</strong><span>Years of hands-on transformation</span></div><div><strong data-count6="200" data-suffix6="+">200+</strong><span>Transformations</span></div><div><strong data-count6="23">23</strong><span>Industrial sectors</span></div><div><strong data-count6="10" data-suffix6="+">10+</strong><span>Countries</span></div></section>
<section class="cap5" id="capabilities" data-chapter6><div class="wrap"><div class="editorial-section-head reveal"><div><p class="eyebrow">FOUR LEVERS OF CHANGE</p><h2>Progress starts<br>in the right place.</h2></div><p>Explore the capabilities that connect<br>your ambition with everyday performance.</p></div><div class="cap-tabs" role="tablist" aria-label="Our capabilities">${CAPABILITIES.map(function(c,i){return `<button role="tab" id="cap-tab-${i}" aria-controls="cap-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-cap="${i}"><span>0${i+1}</span>${c.name}</button>`;}).join('')}</div><div id="cap-panel" class="cap-panel" role="tabpanel" aria-labelledby="cap-tab-0" tabindex="0">${capabilityPanel(0)}</div></div></section>
<section class="stories5 wrap reveal" id="impact" data-chapter6><div class="editorial-section-head"><div><p class="eyebrow">OUR IMPACT</p><h2>Change you can see.<br>Results you can measure.</h2></div><a href="#/our-work" class="text-link">Explore all engagements</a></div><div class="stories5-grid">${[
['steel-di-pipes','MANUFACTURING TRANSFORMATION','$21 million','Recovering the value hidden in everyday operations.','Bottom-line savings in 18 months.'],
['tyre-bead-wire-b2b','SALES & OPERATIONS','10× EBITDA','Creating the conditions for sustained growth.','Transformation over four years.'],
['fmcg-biscuits','DIGITAL ENABLEMENT','$9 million','Turning production insight into action.','Conversion-cost reduction in nine months.']
].map(function(x){return `<a class="story5" href="#/our-work/${x[0]}"><div class="story5-photo"><img src="assets/images/v4/cases/${x[0]}.webp" alt="${esc(x[1])} case study" width="1536" height="1024" loading="lazy"></div><div class="story5-copy"><p class="eyebrow">${x[1]}</p><strong>${x[2]}</strong><h3>${x[3]}</h3><p>${x[4]}</p><span class="story5-read">Read the story</span></div></a>`;}).join('')}</div><p class="portfolio-note">Selected engagement outcomes. Every business starts from a different baseline.</p></section>
<section class="ksa25 wrap reveal" aria-labelledby="ksa25-title"><div class="ksa25-card"><div class="ksa25-photo"><img src="assets/images/v25/saudi-riyadh.webp" alt="Illustrative view of Riyadh’s skyline in warm afternoon light" width="1536" height="1024" loading="lazy"><span>SAUDI ARABIA</span></div><div class="ksa25-copy"><p class="eyebrow">LEVERS FOR CHANGE · SAUDI ARABIA</p><h2 id="ksa25-title">Ambition meets<br><span>possibility.</span></h2><p>A new perspective. The same commitment to lasting performance. Discover Levers for Change in Saudi Arabia.</p><a class="btn btn-blue" href="https://www.lfcksa.com/" target="_blank" rel="noopener noreferrer">Explore LFC Saudi Arabia</a><span class="ksa25-domain">lfcksa.com</span></div></div></section>
<section class="leaders5" id="leadership" data-chapter6><div class="wrap"><div class="editorial-section-head reveal"><div><p class="eyebrow">OUR LEADERSHIP</p><h2>Experience that sees further.<br>People who stay involved.</h2></div><p>Meet the partners and advisors<br>behind Levers for Change.</p></div>${leadershipGrid()}<div class="leaders5-bottom"><a class="text-link" href="https://leversforchange.in/team/">Meet the wider LFC team</a></div></div></section>
<section class="digital5 wrap reveal"><div class="digital5-copy">${cfBrandAI()}<h2>Your plant, connected.<br><span>Your next move, clearer.</span></h2><p>Capture live plant data, see priorities in the Control Tower, and receive AI alerts on WhatsApp or Telegram. ConnectFacts helps your team act while it matters.</p><a class="btn btn-blue" href="#/connectfacts">Explore ConnectFacts AI</a></div><div class="digital5-screen"><div class="cf-official-visual"><img src="assets/connectfacts/control-tower-ai.webp" width="2880" height="1260" alt="ConnectFacts AI Control Tower with live plant priorities" loading="lazy"></div></div></section>
<section class="industry5"><div class="wrap"><div class="editorial-section-head"><div><p class="eyebrow">INDUSTRY EXPERIENCE</p><h2>Grounded in your world.</h2></div><div class="industry3-controls"><button class="control" data-industry-direction="-1" aria-label="Previous industries">Previous</button><button class="control" data-industry-direction="1" aria-label="Next industries">Next</button></div></div><div class="industry3-rail" tabindex="0" aria-label="Explore industries">${INDUSTRY_LENSES.map(function(x){return `<a class="industry3-card" href="#/our-work" data-sector="${esc(x[2])}"><img src="assets/images/v3/${x[1]}.webp" alt="${esc(x[0])} industry" width="1536" height="1024" loading="lazy"><span>${x[0]}</span></a>`;}).join('')}</div></div></section>
<section class="approach5 wrap reveal" id="approach" data-chapter6><div><p class="eyebrow">FROM POSSIBILITY TO PERFORMANCE</p><h2>Think clearly.<br>Act decisively.<br><span>Make it last.</span></h2><a href="#/how-we-engage" class="text-link">Our approach</a></div><ol>${[['01','Understand','Find the losses, quantify the opportunity, and agree where to begin.'],['02','Transform','Work alongside your teams to turn the plan into measured results.'],['03','Sustain','Build the routines, capabilities, and visibility that keep improvement going.']].map(function(x){return '<li><span>'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div></li>';}).join('')}</ol></section>

<section class="closing5"><div class="wrap"><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s discover what’s<br>possible, together.</h2><a class="btn btn-white" href="#/contact">Start a conversation</a></div></section>
`;}};
