  PAGES[""] = { title:"Levers for Change | Turn potential into performance", nav:"", render:function(){
    var featured = ["Tata Steel","Britannia","Godrej","RR Kabel","Welspun","Schneider"];
    var clientLogos = featured.map(function(n){ return LOGOS.find(function(l){return l.name.toLowerCase().replace(/[^a-z]/g, '').indexOf(n.toLowerCase().replace(/[^a-z]/g, '')) !== -1;}); }).filter(Boolean);
    var steel = '#/our-work/' + slugFor('Steel (DI Pipes)');
    return `<section class="new-hero"><div class="wrap">
      <div class="hero-intro"><div><p class="eyebrow">Welcome to Levers for Change</p><h1>Turn potential into<br><em>lasting performance.</em></h1></div>
      <div class="hero-description"><p>From boardroom ambition to shopfloor impact. We work alongside your teams to unlock growth, strengthen operations, and deliver measurable results.</p><a class="btn btn-blue" href="#/what-we-do">Explore what we do</a></div></div>
      <div class="hero-photo"><img src="assets/images/bridge.webp" alt="A sweeping bridge connecting the waterfront to a city skyline in soft morning light" width="1536" height="1024" fetchpriority="high"><div class="hero-caption"><span class="caption-num">16+</span><span>Years of turning business challenges into measurable change.</span></div><a href="#/how-we-engage">Ambition. Action. Impact. &nbsp; ↗</a></div>
      <nav class="hero-topics" aria-label="Explore LFC"><span>In focus</span><a href="#/what-we-do#lever-1">Manufacturing excellence ↗</a><a href="#/what-we-do#lever-2">Profitable growth ↗</a><a href="#/connectfacts">Digital transformation ↗</a><a href="#/our-work">Client impact ↗</a></nav>
    </div></section>
    <section class="home-logos" aria-label="Client relationships"><div class="wrap"><p>Trusted by<br>industry leaders</p><div class="home-logo-row">${clientLogos.map(function(l){return '<img src="'+l.src+'" alt="'+esc(l.name)+'" width="150" height="45">';}).join('')}</div></div></section>
    <section class="section"><div class="wrap"><div class="section-title"><div><p class="eyebrow">Change that counts</p><h2 class="display d2">Real challenges. Tangible impact.</h2></div><a href="#/our-work" class="text-link">Explore our work <span>↗</span></a></div>
      <div class="feature-grid">
        <a class="story" href="${steel}"><div class="story-img"><img src="assets/images/manufacturing.webp" alt="Modern manufacturing equipment on a bright industrial production floor" loading="lazy" width="1536" height="1024"></div><span class="eyebrow">Manufacturing performance</span><h3>Unlocking $21 million in bottom-line savings.</h3><p>An operational turnaround that translated hidden capacity into value over 18 months.</p><span class="story-bottom">Explore the engagement <b>↗</b></span></a>
        <a class="story" href="#/how-we-engage"><div class="story-img"><img src="assets/images/team.webp" alt="Manufacturing professionals working together on the factory floor" loading="lazy" width="1536" height="1024"></div><span class="eyebrow">Our approach</span><h3>On your floor.<br>On your side.</h3><p>Embedded teams. Shared accountability. A fee model linked to verified outcomes.</p><span class="story-bottom">See how we work <b>↗</b></span></a>
        <a class="story" href="#/connectfacts"><div class="story-img story-product"><img src="${CF_DESK}" alt="ConnectFacts live production dashboard" loading="lazy"></div><span class="eyebrow">Digital enablement</span><h3>Better decisions begin with connected facts.</h3><p>Bring your machines, people, and daily decisions together with ConnectFacts.</p><span class="story-bottom">Discover ConnectFacts <b>↗</b></span></a>
      </div></div></section>
    <section class="capability-section"><div class="wrap capability-layout"><div><p class="eyebrow">What we do</p><h2 class="display d2">Four levers.<br>One stronger business.</h2><p class="body">The opportunity is already within your business. We find the right levers, turn insight into action, and help your teams sustain the improvement.</p><a class="text-link" href="#/what-we-do">Explore our capabilities <span>↗</span></a></div><div>
      ${[['01','Manufacturing performance','Recover capacity. Improve quality. Reduce conversion cost.','what-we-do#lever-1'],['02','Sales transformation','Build stronger channels and turn market potential into growth.','what-we-do#lever-2'],['03','Workforce transformation','Align skills, roles, and work with what the business needs.','what-we-do#lever-3'],['04','Shopfloor digitisation','Make every deviation visible and every action accountable.','connectfacts']].map(function(x){return '<a class="lever-row" href="#/'+x[3]+'"><span>'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div><b>↗</b></a>';}).join('')}
    </div></div></section>
    <section class="section"><div class="wrap"><div class="people-section"><img src="assets/images/team.webp" alt="An engineering team reviewing improvement opportunities together" loading="lazy" width="1536" height="1024"><div><p class="eyebrow">The LFC difference</p><h2 class="display d2">We stay for<br>the transformation.</h2><p class="body">We believe the best strategy is one your people can put to work. That is why we spend around 70% of every engagement on site, working shoulder to shoulder with your teams.</p><p class="body">From the first diagnostic to the daily routines that hold the gains, we take ownership of the outcome with you.</p><a class="text-link" href="#/about">Get to know LFC <span>↗</span></a></div></div>
      <div class="home-proof">${[['70+','Documented engagements'],['23','Industrial sectors'],['6','Countries'],['96%+','Success rate under a success-fee model']].map(function(x){return '<div><strong>'+x[0]+'</strong><span>'+x[1]+'</span></div>';}).join('')}</div>
    </div></section>
    <section class="section"><div class="wrap"><div class="digital-band"><div><p class="eyebrow">Meet ConnectFacts</p><h2 class="display d2">Your shopfloor.<br>Connected. In control.</h2><p class="body">Live performance, clear ownership, and actions tracked to closure. Our digital operating platform helps your teams see the right facts and act when it matters.</p><a class="btn btn-blue" href="#/connectfacts">Explore the platform</a></div>${cfShots()}</div></div></section>` + diagBand();
  }};
