var CLIENT_MARKS=__CLIENT_MARKS__;
var LEADERS=__LEADERS__;
function leadershipGrid(){return '<div class="leaders5-grid">'+[2,3,4,5,0,1].map(function(i){var l=LEADERS[i];return '<article class="leader5"><img src="assets/images/leaders/'+l.slug+'.webp" alt="'+esc(l.name)+'" width="1024" height="1024" loading="lazy"><h3>'+esc(l.name)+'</h3><p>'+esc(l.role)+'</p></article>';}).join('')+'</div>';}
function logoRun(hidden){return '<div class="logo5-group"'+(hidden?' aria-hidden="true"':'')+'>'+CLIENT_MARKS.map(function(l){return '<div class="logo5-cell"><img src="'+l.src+'" alt="'+(hidden?'':esc(l.name))+'" width="170" height="70" loading="lazy"></div>';}).join('')+'</div>';}
PAGES['']={title:'Levers for Change | Potential into performance',nav:'',render:function(){return `
<section class="hero5"><div class="hero5-photo"><img src="assets/images/v4/hero-transformation.webp" alt="Industrial engineers collaborating on production improvements" width="1536" height="1024" fetchpriority="high"></div><div class="hero5-shade"></div><div class="wrap hero5-content"><p class="eyebrow">LEVERAGE WHAT’S WITHIN.</p><h1>The potential<br>is there.<br><span>Let’s put it<br>to work.</span></h1><p class="hero5-lede">Sharper operations. Stronger teams. Lasting growth.<br>We turn the possibilities within your business into performance you can measure.</p><div class="hero5-actions"><a href="#/what-we-do" class="btn btn-white">Explore our capabilities</a><a href="#/our-work" class="hero5-link">Discover our impact</a></div></div><div class="hero5-caption">STRATEGY, SHOULDER TO SHOULDER WITH EXECUTION.</div></section>
<section class="clients5" aria-label="Our clients"><div class="wrap clients5-head"><p class="eyebrow">TRUSTED TO MAKE CHANGE HAPPEN</p><button id="logoPause" type="button" aria-pressed="false">Pause logos</button></div><div class="logo5-window"><div class="logo5-track">${logoRun(false)}${logoRun(true)}</div></div></section>
<section class="intro5 wrap reveal"><div><p class="eyebrow">THE VALUE IS ALREADY THERE.</p><h2>A different perspective.<br><span>A tangible difference.</span></h2></div><div><p>Inside every business are opportunities waiting to be seen. We bring the clarity to find them, the experience to act on them, and the commitment to see the change through.</p><a class="text-link" href="#/how-we-engage">How we work</a></div></section>
<section class="proof5 wrap reveal" aria-label="LFC at a glance"><div><strong>16+</strong><span>Years of hands-on transformation</span></div><div><strong>70+</strong><span>Engagements across the portfolio</span></div><div><strong>23</strong><span>Industrial sectors</span></div><div><strong>6</strong><span>Countries</span></div></section>
<section class="cap5"><div class="wrap"><div class="editorial-section-head reveal"><div><p class="eyebrow">FOUR LEVERS OF CHANGE</p><h2>Progress starts<br>in the right place.</h2></div><p>Explore the capabilities that connect<br>your ambition with everyday performance.</p></div><div class="cap-tabs" role="tablist" aria-label="Our capabilities">${CAPABILITIES.map(function(c,i){return `<button role="tab" id="cap-tab-${i}" aria-controls="cap-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-cap="${i}"><span>0${i+1}</span>${c.name}</button>`;}).join('')}</div><div id="cap-panel" class="cap-panel" role="tabpanel" aria-labelledby="cap-tab-0" tabindex="0">${capabilityPanel(0)}</div></div></section>
<section class="stories5 wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">OUR IMPACT</p><h2>Change you can see.<br>Results you can measure.</h2></div><a href="#/our-work" class="text-link">Explore all engagements</a></div><div class="stories5-grid">${[
['steel-di-pipes','MANUFACTURING TRANSFORMATION','$21 million','Recovering the value hidden in everyday operations.','Bottom-line savings in 18 months.'],
['tyre-bead-wire-b2b','SALES & OPERATIONS','10× EBITDA','Creating the conditions for sustained growth.','Transformation over four years.'],
['fmcg-biscuits','DIGITAL ENABLEMENT','$9 million','Turning production insight into action.','Conversion-cost reduction in nine months.']
].map(function(x){return `<a class="story5" href="#/our-work/${x[0]}"><div class="story5-photo"><img src="assets/images/v4/cases/${x[0]}.webp" alt="${esc(x[1])} case study" width="1536" height="1024" loading="lazy"></div><div class="story5-copy"><p class="eyebrow">${x[1]}</p><strong>${x[2]}</strong><h3>${x[3]}</h3><p>${x[4]}</p><span class="story5-read">Read the story</span></div></a>`;}).join('')}</div><p class="portfolio-note">Selected engagement outcomes. Every business starts from a different baseline.</p></section>
<section class="leaders5" id="leadership"><div class="wrap"><div class="editorial-section-head reveal"><div><p class="eyebrow">OUR LEADERSHIP</p><h2>Experience that sees further.<br>People who stay involved.</h2></div><p>Meet the partners and advisors<br>behind Levers for Change.</p></div>${leadershipGrid()}<div class="leaders5-bottom"><a class="text-link" href="https://leversforchange.in/team/">Meet the wider LFC team</a></div></div></section>
<section class="digital5 wrap reveal"><div class="digital5-copy"><p class="eyebrow">CONNECTFACTS</p><h2>Know what’s happening.<br><span>Change what happens next.</span></h2><p>Connect live performance with clear ownership. Give your people the facts to make better decisions, act sooner, and sustain the gains.</p><a class="btn btn-blue" href="#/connectfacts">Explore ConnectFacts</a></div><div class="digital5-screen">${cfShots()}</div></section>
<section class="industry5"><div class="wrap"><div class="editorial-section-head"><div><p class="eyebrow">INDUSTRY EXPERIENCE</p><h2>Grounded in your world.</h2></div><div class="industry3-controls"><button class="control" data-industry-direction="-1" aria-label="Previous industries">Previous</button><button class="control" data-industry-direction="1" aria-label="Next industries">Next</button></div></div><div class="industry3-rail" tabindex="0" aria-label="Explore industries">${INDUSTRY_LENSES.map(function(x){return `<a class="industry3-card" href="#/our-work" data-sector="${esc(x[2])}"><img src="assets/images/v3/${x[1]}.webp" alt="${esc(x[0])} industry" width="1536" height="1024" loading="lazy"><span>${x[0]}</span></a>`;}).join('')}</div></div></section>
<section class="approach5 wrap reveal"><div><p class="eyebrow">FROM POSSIBILITY TO PERFORMANCE</p><h2>Think clearly.<br>Act decisively.<br><span>Make it last.</span></h2><a href="#/how-we-engage" class="text-link">Our approach</a></div><ol>${[['01','Understand','Find the losses, quantify the opportunity, and agree where to begin.'],['02','Transform','Work alongside your teams to turn the plan into measured results.'],['03','Sustain','Build the routines, capabilities, and visibility that keep improvement going.']].map(function(x){return '<li><span>'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div></li>';}).join('')}</ol></section>
<section class="closing5"><div class="wrap"><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s discover what’s<br>possible, together.</h2><a class="btn btn-white" href="#/contact">Start a conversation</a></div></section>
`;}};
