  var CAPABILITIES = [
    {name:'Manufacturing',image:'v3/03-operations',title:'Unlock the capacity you already own.',text:'Improve availability, stabilise processes, and recover the losses hidden in everyday operations. Turn your plant’s installed potential into measurable performance.',metric:'+15–80%',label:'Throughput improvement across the portfolio',href:'#/what-we-do#lever-1'},
    {name:'Sales',image:'v3/04-commercial',title:'Turn market opportunity into meaningful growth.',text:'Build stronger channels, improve conversion, and connect commercial ambition with operational reliability. Make your business easier to buy from and harder to replace.',metric:'3–5×',label:'Sales conversion improvement across the portfolio',href:'#/what-we-do#lever-2'},
    {name:'People',image:'v3/05-people',title:'Better work starts with better ways of working.',text:'Align roles, skills, and technology with the work that matters. Build productive teams and practical operating structures grounded in evidence.',metric:'23',label:'Industrial sectors in our engagement portfolio',href:'#/what-we-do#lever-3'},
    {name:'Digital',image:'v3/06-connected',title:'The right facts. In the right hands.',text:'Live performance, a clear owner for every deviation, and actions tracked to closure. ConnectFacts makes everyday decisions more informed and accountable.',metric:'12+',label:'ConnectFacts installations',href:'#/connectfacts'}
  ];
  var INDUSTRY_LENSES = [
    ['Steel','10-steel','steel'],['Pipes & polymers','17-polymers','pipes'],['Food & ingredients','13-food','food'],['Automotive','16-automotive','auto'],['Textiles','14-textiles','fabric'],['Pharmaceuticals','15-pharma','API'],['Cement','24-cement','cement'],['Electrical equipment','23-electrical','electrical'],['Foundry & castings','12-foundry','castings'],['Dairy','21-dairy','dairy'],['Wires & cables','19-cables','cables'],['Non-ferrous metals','18-metals','copper'],['Technical ceramics','22-ceramics','ceramics'],['Industrial engineering','20-engineering','engineering'],['Agricultural processing','26-agriculture','agri'],['Supply chain','25-logistics','logistics'],['Export growth','28-export','export'],['Ductile iron pipes','11-pipes','ductile']
  ];
  function capabilityPanel(index){var c=CAPABILITIES[index];return `<div class="cap-visual"><img src="assets/images/${c.image}.webp" alt="${esc(c.name)} transformation" width="1536" height="1024"><div class="cap-metric"><strong>${c.metric}</strong><span>${c.label}</span></div></div><div class="cap-copy"><p class="eyebrow">0${index+1} / FOUR LEVERS OF CHANGE</p><h3>${c.title}</h3><p>${c.text}</p><a class="btn btn-blue" href="${c.href}">Explore ${c.name.toLowerCase()}</a></div>`;}
  PAGES['']={title:'Levers for Change | Unlock the value within',nav:'',render:function(){return `
    <div class="hero4-band"><section class="hero3 wrap"><div class="hero3-copy"><p class="eyebrow"><span class="brand-dot"></span> STRATEGY, PUT TO WORK.</p><h1>Extraordinary<br>potential.<br><span>Already yours.</span></h1><p class="hero3-description">A stronger business begins with what’s within it. We help you see the opportunity, activate the right levers, and turn ambition into lasting performance.</p><div class="hero3-actions"><a href="#/what-we-do" class="btn btn-blue">Discover your possibilities</a><a href="#/our-work" class="text-link">Our impact <span>↗</span></a></div><div class="hero3-note"><span>16+ years</span><p>On the floor. With your people.<br>Accountable for the outcome.</p></div></div><div class="hero3-art"><div class="hero3-image"><img src="assets/images/v4/hero-transformation.webp" alt="Industrial engineer and plant manager improving production together" width="1536" height="1024" fetchpriority="high"><span class="hero3-image-label">WORKING TOGETHER. MAKING CHANGE REAL.</span></div><div class="hero3-inset"><img src="assets/images/v3/29-quality.webp" alt="Precision inspection of a machined gear" width="1536" height="1024"><div><span>THE DETAIL MAKES THE DIFFERENCE</span><a href="#/how-we-engage" aria-label="Discover our approach">↗</a></div></div><span class="hero3-index">01 — LEVERS FOR CHANGE</span></div></section></div>
    <section class="brand-strip wrap reveal" aria-label="Selected client relationships"><p>TRUSTED TO MAKE CHANGE HAPPEN</p><div>${['Tata Steel','Britannia','Godrej','RR Kabel','Welspun','Schneider'].map(function(n){var l=LOGOS.find(function(l){return l.name.toLowerCase().replace(/[^a-z]/g,'').includes(n.toLowerCase().replace(/[^a-z]/g,''));});return l?'<img src="'+l.src+'" alt="'+esc(l.name)+'" width="150" height="50" loading="lazy">':'';}).join('')}</div></section>
    <section class="intro3 wrap reveal"><p class="eyebrow">INSIGHT IS THE BEGINNING.</p><h2>Real change happens<br>when <span>thinking meets doing.</span></h2><div><p>We work where the value is created. Alongside your teams, we connect strategic clarity with the everyday decisions that make a business perform.</p><a href="#/how-we-engage" class="text-link">See how we work <span>↗</span></a></div></section>
    <section class="capabilities-section wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">FOUR LEVERS. ONE STRONGER BUSINESS.</p><h2>Where can you go further?</h2></div><p>Choose a capability to explore<br>the possibilities within your business.</p></div><div class="cap-tabs" role="tablist" aria-label="Our capabilities">${CAPABILITIES.map(function(c,i){return `<button role="tab" id="cap-tab-${i}" aria-controls="cap-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-cap="${i}"><span>0${i+1}</span>${c.name}<b>↗</b></button>`;}).join('')}</div><div id="cap-panel" class="cap-panel" role="tabpanel" aria-labelledby="cap-tab-0" tabindex="0">${capabilityPanel(0)}</div></section>
    <div class="impact4-band"><section class="work3 wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">MEASURABLE CHANGE</p><h2>The difference, delivered.</h2></div><a class="text-link" href="#/our-work">Explore all engagements <span>↗</span></a></div><div class="work3-grid">${[
      ['steel-di-pipes','OPERATIONAL TURNAROUND','$21 million','From hidden losses to bottom-line value.','Savings delivered in 18 months.','Steel (DI Pipes)'],
      ['tyre-bead-wire-b2b','SALES + OPERATIONS','10× EBITDA','A business built to grow further.','Transformation over four years.','Tyre Bead Wire (B2B)'],
      ['fmcg-biscuits','DIGITAL ENABLEMENT','$9 million','Every fact became an opportunity.','Conversion-cost reduction in nine months.','FMCG Biscuits']
    ].map(function(x){return `<a class="work3-card" href="#/our-work/${slugFor(x[5])}"><div class="work3-photo"><img src="assets/images/v4/cases/${x[0]}.webp" alt="${esc(x[5])} industry" width="1536" height="1024" loading="lazy"><span aria-hidden="true">↗</span></div><p class="eyebrow">${x[1]}</p><strong>${x[2]}</strong><h3>${x[3]}</h3><p>${x[4]}</p></a>`;}).join('')}</div><p class="portfolio-note">Selected outcomes from completed engagements. Every business starts from a different baseline.</p></section></div>
    <section class="industry3 wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">INDUSTRY FLUENCY</p><h2>Your world.<br>Understood.</h2></div><div class="industry3-controls"><p>Different industries.<br>The same commitment to getting it right.</p><button class="control" data-industry-direction="-1" aria-label="Previous industries">←</button><button class="control" data-industry-direction="1" aria-label="Next industries">→</button></div></div><div class="industry3-rail" tabindex="0" aria-label="Explore industries">${INDUSTRY_LENSES.map(function(x){return `<a class="industry3-card" href="#/our-work" data-sector="${esc(x[2])}"><img src="assets/images/v3/${x[1]}.webp" alt="${esc(x[0])} industry" width="1536" height="1024" loading="lazy"><span>${x[0]} <b>↗</b></span></a>`;}).join('')}</div></section>
    <section class="digital3 wrap reveal"><div class="digital3-content"><p class="eyebrow">CONNECTFACTS / THE DIGITAL OPERATING LAYER</p><h2>Clarity, connected<br>to action.</h2><p>See performance as it happens. Give every issue an owner. Follow every action to closure. ConnectFacts brings the work, the people, and the facts together.</p><a class="btn btn-blue" href="#/connectfacts">Discover ConnectFacts</a><div class="digital3-tags"><span>Live visibility</span><span>Clear ownership</span><span>Lasting improvement</span></div></div><div class="digital3-visual"><div class="digital3-context"><img src="assets/images/v3/06-connected.webp" alt="An industrial sensor connected to production equipment" width="1536" height="1024" loading="lazy"></div><div class="digital3-screen">${cfShots()}</div></div></section>
    <div class="people4-band"><section class="people3 wrap reveal"><div class="people3-image"><img src="assets/images/v3/02-strategy.webp" alt="Indian business professionals collaborating in a light-filled boardroom" width="1536" height="1024" loading="lazy"><p>SHARED AMBITION. SHARED ACCOUNTABILITY.</p></div><div class="people3-copy"><p class="eyebrow">MEET LEVERS FOR CHANGE</p><h2>Good people.<br>Real commitment.<br><span>Meaningful change.</span></h2><p>Our work is personal. We learn your business, work with your people, and stay involved through execution. Because a transformation is only as good as the difference it leaves behind.</p><a class="text-link" href="#/about">Get to know LFC <span>↗</span></a><div class="about-stats"><div><strong>70+</strong><span>Engagements</span></div><div><strong>23</strong><span>Industrial sectors</span></div><div><strong>6</strong><span>Countries</span></div></div></div></section></div>
    <section class="journey3 wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">THE PATH TO BETTER</p><h2>From possibility to performance.</h2></div><a class="text-link" href="#/how-we-engage">Our approach <span>↗</span></a></div><div class="journey3-grid">${[['07-diagnostic','01','Understand','See the losses. Size the opportunity. Build a shared view of what is possible.'],['08-execution','02','Transform','Embed the right team, activate the levers, and turn the plan into measured results.'],['09-sustain','03','Sustain','Build the routines, capabilities, and digital visibility that keep the gains in place.']].map(function(x){return `<a href="#/how-we-engage" class="journey3-card"><img src="assets/images/v3/${x[0]}.webp" alt="${x[2]} phase of a business transformation" width="1536" height="1024" loading="lazy"><div><span>${x[1]}</span><h3>${x[2]}</h3><p>${x[3]}</p><b aria-hidden="true">↗</b></div></a>`;}).join('')}</div></section>
    <section class="resource3 wrap reveal"><img src="assets/images/v3/27-energy.webp" alt="Solar installation beside a modern white industrial building" width="1536" height="1024" loading="lazy"><div><p class="eyebrow">RESOURCE PRODUCTIVITY</p><h2>Better use of today.<br>More possibility tomorrow.</h2><p>Reduce waste, improve energy performance, and build a more efficient business through everyday operational excellence.</p><a class="btn btn-outline" href="#/what-we-do#lever-1">Explore operational excellence</a></div></section>
    <div class="closing4-band"><section class="closing3 wrap reveal"><div><p class="eyebrow">LET’S FIND YOUR NEXT OPPORTUNITY</p><h2>What’s possible<br><span>within your business?</span></h2></div><div><p>Start with a conversation.<br>Build a clearer picture of what comes next.</p><a class="btn btn-blue" href="#/contact">Talk to our team</a></div></section></div>
  `;}};
