  var EDITORIAL_SLIDES = [
    {image:'logistics',category:'SALES TRANSFORMATION',title:'Turn market presence into market leadership.',text:'Stronger channels. Greater reach. Profitable growth.',href:'#/what-we-do#lever-2'},
    {image:'digital',category:'CONNECTED INTELLIGENCE',title:'Make every fact a catalyst for change.',text:'Connect your machines, your people, and your next decision.',href:'#/connectfacts'},
    {image:'manufacturing',category:'MANUFACTURING EXCELLENCE',title:'The next stage of growth is already on your floor.',text:'Discover the capacity and performance within your business.',href:'#/what-we-do#lever-1'},
    {image:'team',category:'THE HUMAN SIDE OF CHANGE',title:'Transformation happens together.',text:'We work alongside your people to make the gains last.',href:'#/how-we-engage'},
    {image:'energy',category:'RESOURCE PRODUCTIVITY',title:'Less waste. More possibility.',text:'Better operations create a stronger, more efficient business.',href:'#/our-work'},
    {image:'bridge',category:'ABOUT LEVERS FOR CHANGE',title:'Connecting ambition with real-world impact.',text:'Since 2009. On the floor. Accountable for the outcome.',href:'#/about'}
  ];
  var CAPABILITIES = [
    {name:'Manufacturing performance',image:'manufacturing',title:'More from the capacity you already own.',text:'Improve availability, stabilise processes, and recover the losses hidden in everyday operations. We turn the installed potential of your plant into measurable performance.',metric:'+15–80%',label:'Throughput improvement across the portfolio',href:'#/what-we-do#lever-1'},
    {name:'Sales transformation',image:'logistics',title:'Build a business that reaches further.',text:'Redesign channels, strengthen conversion, and connect commercial ambition to operational reliability. Make every market opportunity work harder.',metric:'3–5×',label:'Sales conversion improvement across the portfolio',href:'#/what-we-do#lever-2'},
    {name:'Workforce transformation',image:'team',title:'The right work. The right capabilities.',text:'Understand work at the role level. Align skills, team structures, and technology to improve productivity and build an organisation ready for what comes next.',metric:'23',label:'Industrial sectors in our engagement portfolio',href:'#/what-we-do#lever-3'},
    {name:'Shopfloor digitisation',image:'digital',title:'Connect the facts. Change the outcome.',text:'Live OEE, a named owner for every deviation, and actions tracked to closure. ConnectFacts puts useful information into the hands of the people who can act.',metric:'12+',label:'ConnectFacts installations',href:'#/connectfacts'}
  ];
  function capabilityPanel(index){ var c=CAPABILITIES[index]; return `<div class="cap-visual"><img src="assets/images/${c.image}.webp" alt="${esc(c.name)}" width="1536" height="1024"><div class="cap-metric"><strong>${c.metric}</strong><span>${c.label}</span></div></div><div class="cap-copy"><p class="eyebrow">${String(index+1).padStart(2,'0')} / OUR CAPABILITIES</p><h3>${c.title}</h3><p>${c.text}</p><a class="btn btn-blue" href="${c.href}">Explore this capability</a></div>`; }
  PAGES[""] = { title:"Levers for Change | Where ambition becomes impact", nav:"", render:function(){
    return `<section class="editorial-hero" aria-labelledby="hero-title"><div class="hero-heading"><p class="eyebrow">WELCOME TO LEVERS FOR CHANGE</p><h1 id="hero-title">Where ambition becomes<br><em>extraordinary impact.</em></h1><p>Clarity in strategy. Commitment in execution.</p></div>
    <div class="showcase" aria-roledescription="carousel" aria-label="Explore Levers for Change" tabindex="0"><div class="showcase-track">${EDITORIAL_SLIDES.map(function(s,i){return `<article class="showcase-card ${i===2?'is-active':''}" aria-roledescription="slide" aria-label="${i+1} of ${EDITORIAL_SLIDES.length}"><img src="assets/images/${s.image}.webp" alt="${esc(s.category.toLowerCase())}" width="1024" height="1536" ${i===2?'fetchpriority="high"':''}><span class="image-category">${s.category}</span><a class="glass-caption" href="${s.href}" ${i!==2?'tabindex="-1"':''}><span class="caption-kind">PERSPECTIVE &nbsp; / &nbsp; LEVERS FOR CHANGE</span><h2>${s.title}</h2><span class="caption-reveal">${s.text}<b>Explore the possibilities <span>↗</span></b></span><span class="caption-arrow" aria-hidden="true">↗</span></a></article>`;}).join('')}</div></div>
    <div class="showcase-controls wrap"><div class="control-cluster"><button class="control" id="showcasePlay" aria-label="Play slideshow" aria-pressed="false">▷</button><span class="control-divider"></span><button class="control" id="showcasePrev" aria-label="Previous story">←</button><button class="control" id="showcaseNext" aria-label="Next story">→</button></div><div class="slide-dots" aria-label="Choose a story">${EDITORIAL_SLIDES.map(function(s,i){return `<button aria-label="Show story ${i+1}: ${esc(s.category.toLowerCase())}" aria-pressed="${i===2}" data-slide="${i}"><span></span></button>`;}).join('')}</div><span class="slide-count" aria-live="polite">03 / 06</span></div>
    <nav class="spotlight" aria-label="LFC spotlight"><span>LFC SPOTLIGHT</span><a href="#/what-we-do#lever-1">OPERATIONAL EXCELLENCE</a><a href="#/connectfacts">CONNECTFACTS</a><a href="#/our-work">CLIENT IMPACT</a></nav></section>
    <section class="impact-statement wrap reveal"><div><p class="eyebrow">CHANGE THAT COUNTS</p><h2>Transformative impact.<br>Built together.</h2></div><div><p>We stand shoulder to shoulder with your teams to turn complex challenges into lasting advantage. From the boardroom to the shopfloor, we stay accountable for the outcome.</p><a class="btn btn-white" href="#/our-work">Explore client impact</a></div></section>
    <section class="brand-strip wrap reveal" aria-label="Selected client relationships"><p>TRUSTED ON THE SHOPFLOOR BY INDUSTRY LEADERS</p><div>${['Tata Steel','Britannia','Godrej','RR Kabel','Welspun','Schneider'].map(function(n){var l=LOGOS.find(function(l){return l.name.toLowerCase().replace(/[^a-z]/g,'').includes(n.toLowerCase().replace(/[^a-z]/g,''));});return l?'<img src="'+l.src+'" alt="'+esc(l.name)+'" width="150" height="50" loading="lazy">':'';}).join('')}</div></section>
    <section class="capabilities-section wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">WHAT WE DO</p><h2>Find your next advantage.</h2></div><p>Four connected capabilities.<br>One focus: your business performance.</p></div><div class="cap-tabs" role="tablist" aria-label="Our capabilities">${CAPABILITIES.map(function(c,i){return `<button role="tab" id="cap-tab-${i}" aria-controls="cap-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-cap="${i}"><span>0${i+1}</span>${c.name}<b>↗</b></button>`;}).join('')}</div><div id="cap-panel" class="cap-panel" role="tabpanel" aria-labelledby="cap-tab-0" tabindex="0">${capabilityPanel(0)}</div></section>
    <section class="work-section wrap reveal"><div class="editorial-section-head"><div><p class="eyebrow">THE PROOF IS IN THE PROGRESS</p><h2>What change looks like.</h2></div><a class="text-link" href="#/our-work">Discover our work <span>↗</span></a></div><div class="impact-grid">
    <a class="large-story image-story" href="#/our-work/${slugFor('Steel (DI Pipes)')}"><img src="assets/images/manufacturing.webp" alt="Precision manufacturing plant" loading="lazy"><div class="image-story-copy"><p class="eyebrow">OPERATIONAL TURNAROUND · STEEL</p><strong>$21 million</strong><h3>Turning hidden opportunity<br>into bottom-line savings.</h3><span class="story-link">See the 18-month transformation <b>↗</b></span></div></a>
    <div class="stacked-stories"><a class="small-story" href="#/our-work/${slugFor('Tyre Bead Wire (B2B)')}"><img src="assets/images/logistics.webp" alt="Ordered shipping containers in a port" loading="lazy"><div><p class="eyebrow">SALES + OPERATIONS</p><h3>10× EBITDA.<br>A stronger growth engine.</h3><span>Four years of transformation <b>↗</b></span></div></a><a class="small-story blue-story" href="#/our-work/${slugFor('FMCG Biscuits')}"><img src="assets/images/digital.webp" alt="Flowing network of blue optical fibres" loading="lazy"><div><p class="eyebrow">DIGITAL TRANSFORMATION</p><h3>$9 million.<br>The value of visibility.</h3><span>Conversion-cost reduction in 9 months <b>↗</b></span></div></a></div></div></section>
    <section class="digital-feature wrap reveal"><div class="digital-intro"><p class="eyebrow">INTRODUCING CONNECTFACTS</p><h2>A clearer view.<br>A better next move.</h2><p>Give every level of your organisation the facts to act. Our digital operating platform connects live performance with everyday decisions.</p><a class="btn btn-blue" href="#/connectfacts">Discover ConnectFacts</a></div><div class="digital-product"><div class="product-topline"><span><i></i> CONNECTED OPERATIONS</span><span>FLOOR → LEADERSHIP</span></div>${cfShots()}<div class="product-bottomline"><span>SEE THE LOSS</span><span>OWN THE ACTION</span><span>SUSTAIN THE GAIN</span></div></div></section>
    <section class="about-feature wrap reveal"><div class="about-photo"><img src="assets/images/team.webp" alt="Manufacturing team reviewing a tablet on the shopfloor" loading="lazy"><span>THE HUMAN SIDE OF TRANSFORMATION</span></div><div><p class="eyebrow">MEET LEVERS FOR CHANGE</p><h2>The difference<br>is in the doing.</h2><p>Great ideas matter. What happens next matters more. Since 2009, we have helped manufacturers build the capabilities, routines, and confidence to make change stick.</p><a class="btn btn-outline" href="#/about">Get to know us</a><div class="about-stats"><div><strong>70+</strong><span>Engagements</span></div><div><strong>23</strong><span>Industrial sectors</span></div><div><strong>6</strong><span>Countries</span></div></div></div></section>
    <section class="landscape-feature wrap reveal"><img src="assets/images/energy.webp" alt="Renewable energy infrastructure across a green landscape" loading="lazy"><div><p class="eyebrow">RESOURCE PRODUCTIVITY</p><h2>A more efficient business.<br>A more resilient future.</h2><a class="btn btn-white" href="#/what-we-do#lever-1">Explore the opportunity</a></div></section>
    <section class="engagement-section wrap reveal"><div><p class="eyebrow">HOW CHANGE HAPPENS</p><h2>A clear path.<br>A shared commitment.</h2><a class="text-link" href="#/how-we-engage">Our approach <span>↗</span></a></div><div class="engagement-steps">${[['01','See the opportunity','A focused diagnostic to understand the losses, size the prize, and establish what is possible.'],['02','Make it happen','An embedded team, clear ownership, and a programme linked to verified outcomes.'],['03','Make it last','Digital visibility and stronger daily routines, so the improvement stays when we leave.']].map(function(x,i){return `<details ${i===0?'open':''}><summary><span>${x[0]}</span>${x[1]}<b>+</b></summary><p>${x[2]}</p></details>`;}).join('')}</div></section>
    <section class="closing-band wrap reveal"><p class="eyebrow">LET’S MOVE FORWARD</p><h2>What could change<br>make possible for you?</h2><a class="btn btn-blue" href="#/contact">Start a conversation</a><span>Ambition. Action. Impact.</span></section>`;
  }};
