function renderServices23(levers){
  var copy=[
    {title:'More output. From what you already own.',text:'Find the losses holding your plant back. Improve reliability, quality and flow to turn installed capacity into profitable output.',image:'images/v6/precision.webp',alt:'Precision manufacturing equipment',tags:['Production flow','Maintenance & reliability','Energy & quality'],metric:'+15–80%',label:'Throughput improvement across the portfolio',link:'#/our-work/steel-di-pipes',cta:'Explore a manufacturing transformation'},
    {title:'Turn market potential into profitable growth.',text:'Build stronger channels, improve sales conversion and align supply with demand. Give your teams a clear path from opportunity to revenue.',image:'images/v6/growth.webp',alt:'Commercial growth and distribution',tags:['Channel strategy','Sales execution','Export growth'],metric:'3–5×',label:'Sales conversion improvement across the portfolio',link:'#/our-work/tyre-bead-wire-b2b',cta:'Explore a growth transformation'},
    {title:'Better ways of working. Stronger teams.',text:'Align work, skills and technology with what your business needs. Build practical improvements with the people who will make them last.',image:'images/v3/05-people.webp',alt:'Team collaborating on operational improvement',tags:['Work design','Skills & deployment','Practical automation'],metric:'+15–25 pts',label:'Workforce utilisation improvement across engagements',link:'https://leversforchange.in/work-force-transformation/',cta:'Explore workforce transformation'},
    {title:'See clearly. Act sooner.',text:'Connect daily operating data with the people who can act on it. ConnectFacts brings performance, ownership and follow-through into one place.',image:'connectfacts/actions-dashboard.webp',alt:'ConnectFacts performance dashboard',tags:['Live performance','Clear ownership','Action tracking'],metric:'12+',label:'ConnectFacts installations',link:'#/connectfacts',cta:'Explore ConnectFacts'}
  ];
  return `<div class="services23"><section class="s23-hero wrap"><div><p class="eyebrow">WHAT WE DO</p><h1>Find the potential.<br><span>Make it perform.</span></h1><p>Four connected capabilities. One ambition: a stronger, more profitable business.</p><a class="btn btn-blue" href="#/contact">Find your growth opportunity</a></div><div class="s23-hero-photo"><img src="assets/images/v3/08-execution.webp" alt="Consulting team working alongside operations teams" fetchpriority="high"><span>ON THE FLOOR. WITH YOUR PEOPLE.</span></div></section>
  <nav class="s23-nav wrap" aria-label="Explore our capabilities">${levers.map((l,i)=>`<a href="#/what-we-do#${l.id}"><span>0${i+1}</span>${esc(l.name)}</a>`).join('')}</nav>
  <div class="s23-services">${levers.map((l,i)=>{var c=copy[i];return `<section class="s23-service wrap" id="${l.id}"><div class="s23-visual ${i===3?'s23-dashboard':''}"><img src="assets/${c.image}" alt="${c.alt}" loading="lazy"><div class="s23-result"><strong>${c.metric}</strong><span>${c.label}</span></div></div><div class="s23-copy"><p class="eyebrow">0${i+1} / ${esc(l.name)}</p><h2>${c.title}</h2><p>${c.text}</p><ul class="s23-tags">${c.tags.map(t=>`<li>${t}</li>`).join('')}</ul><a class="text-link" href="${c.link}">${c.cta}</a><details><summary>Inside the engagement</summary><p>${esc(i===2?'We measure work content, align roles with skills, and develop a practical sequence of workflow improvements, automation and digital support. Each change is tested with the area team.':l.body)}</p><ul>${l.proof.slice(0,2).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></details></div></section>`;}).join('')}</div>
  <section class="s23-close"><div class="wrap"><p class="eyebrow">YOUR STARTING POINT</p><h2>What would better<br>performance look like?</h2><p>Tell us where progress is getting stuck. Together, we’ll identify the right place to begin.</p><a class="btn btn-white" href="#/contact">Start a conversation</a><a href="#/our-work" class="s23-impact">See our impact</a></div></section></div>`;
}
